{
  "branches": ["main"],
  "plugins":
    [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github",
      [
        "@codedependant/semantic-release-docker",
        {
          "dockerRegistry": "ghcr.io",
          "dockerProject": "betagouv",
          "dockerImage": "matomo-to-pg/sync",
          "dockerTags":
            [
              "{{major}}.{{minor}}.{{patch}}",
              "{{major}}.{{minor}}",
              "{{major}}-latest",
              "{{git_sha}}",
              "latest",
            ],
          "dockerArgs":
            {
              "BUILD_VERSION": "{{major}}.{{minor}}.{{patch}}",
              "COMMIT_SHA": "{{git_sha}}",
            },
        },
      ],
    ],
}
