name: ✨ Release

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    # tags:
    #   - "*" # Push events to every tag not containing /
    branches:
      - main
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        # with:
        #   extra_plugins: |
        #     @semantic-release/changelog@6.0.0
        #     @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
